language: python
python: "2.7"
sudo: true

install:
  # Install Ansible.
  - sudo pip install ansible
 
script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i hosts playbook.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i hosts playbook.yml --connection=local --sudo -vvvv"
